#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

case=$(pwd)

# Make 3D mesh
cd $case/mesh || exit
./Allrun


# Initialize and verify with steady
cd $case/steady || exit
./Allrun


# Run wake with sliding mesh
cd $case/unsteady || exit
./Allrun

#------------------------------------------------------------------------------
