#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

case=$(pwd)

# Make 3D mesh
cd $case/turbine || exit
./Allrun

# Make 3D mesh
cd $case/domain || exit
./Allrun

#------------------------------------------------------------------------------
